angular.module('kityminderEditor').service('lang.en', function() {
  return {
    en: {
      template: {
        default: 'Mind Map',
        tianpan: 'Tianpan',
        structure: 'Org Chart',
        filetree: 'File Tree',
        right: 'Logic Chart',
        'fish-bone': 'Fishbone',
      },
      theme: {
        classic: 'Classic',
        'classic-compact': 'Compact Classic',
        snow: 'Snow',
        'snow-compact': 'Compact Snow',
        fish: 'Fishbone',
        wire: 'Wireframe',
        'fresh-red': 'Fresh Red',
        'fresh-soil': 'Fresh Soil',
        'fresh-green': 'Fresh Green',
        'fresh-blue': 'Fresh Blue',
        'fresh-purple': 'Fresh Purple',
        'fresh-pink': 'Fresh Pink',
        'fresh-red-compat': 'Compact Red',
        'fresh-soil-compat': 'Compact Soil',
        'fresh-green-compat': 'Compact Green',
        'fresh-blue-compat': 'Compact Blue',
        'fresh-purple-compat': 'Compact Purple',
        'fresh-pink-compat': 'Compact Pink',
        tianpan: 'Classic Tianpan',
        'tianpan-compact': 'Compact Tianpan',
      },
      maintopic: 'Central Topic',
      topic: 'Topic',
      panels: {
        history: 'History',
        template: 'Template',
        theme: 'Theme',
        layout: 'Layout',
        style: 'Style',
        font: 'Font',
        color: 'Color',
        background: 'Background',
        insert: 'Insert',
        arrange: 'Arrange',
        nodeop: 'Current',
        priority: 'Priority',
        progress: 'Progress',
        resource: 'Resource',
        note: 'Note',
        attachment: 'Attachment',
        word: 'Text',
      },
      error_message: {
        title: 'Mind map error',

        err_load: 'Failed to load the mind map',
        err_save: 'Failed to save the mind map',
        err_network: 'Network error',
        err_doc_resolve: 'Failed to parse the document',
        err_unknown: 'An unexpected error occurred',
        err_localfile_read: 'Failed to read the file',
        err_download: 'Failed to download the file',
        err_remove_share: 'Failed to remove sharing',
        err_create_share: 'Failed to share',
        err_mkdir: 'Failed to create the folder',
        err_ls: 'Failed to read the folder',
        err_share_data: 'Failed to load shared content',
        err_share_sync_fail: 'Failed to sync shared content',
        err_move_file: 'Failed to move the file',
        err_rename: 'Failed to rename the file',

        unknownreason: 'Unknown reason',
        pcs_code: {
          3: 'This API is not supported',
          4: 'You do not have permission to perform this action',
          5: 'IP address is not authorized',
          110: 'Your session has expired. Please sign in again',
          31001: 'Database query error',
          31002: 'Database connection error',
          31003: 'Database returned no results',
          31021: 'Network error',
          31022: 'Unable to connect to the server',
          31023: 'Invalid input parameter',
          31024: 'App ID is empty',
          31025: 'Backend storage error',
          31041: 'Invalid user cookie',
          31042: 'User is not signed in',
          31043: 'User is not activated',
          31044: 'User is not authorized',
          31045: 'User does not exist',
          31046: 'User already exists',
          31061: 'File already exists',
          31062: 'Invalid file name',
          31063: 'Parent folder does not exist',
          31064: 'You do not have permission to access this file',
          31065: 'Folder is full',
          31066: 'File does not exist',
          31067: 'File processing error',
          31068: 'Failed to create the file',
          31069: 'Failed to copy the file',
          31070: 'Failed to delete the file',
          31071: 'Failed to read file metadata',
          31072: 'Failed to move the file',
          31073: 'Failed to rename the file',
          31079: 'File MD5 was not found. Upload the whole file with the upload API.',
          31081: 'Failed to create the superfile',
          31082: 'The superfile block list is empty',
          31083: 'Failed to update the superfile',
          31101: 'Internal tag system error',
          31102: 'Invalid tag parameter',
          31103: 'Tag system error',
          31110: 'Not authorized to set a quota for this folder',
          31111: 'Quota management supports only two folder levels',
          31112: 'Quota exceeded',
          31113: 'Quota cannot exceed an ancestor folder quota',
          31114: 'Quota cannot be smaller than a child folder quota',
          31141: 'Failed to request the thumbnail service',
          31201: 'Signature error',
          31202: 'File does not exist',
          31203: 'Failed to set ACL',
          31204: 'Failed to request ACL verification',
          31205: 'Failed to get ACL',
          31206: 'ACL does not exist',
          31207: 'Bucket already exists',
          31208: 'Invalid user request',
          31209: 'Server error',
          31210: 'Server does not support this request',
          31211: 'Access denied',
          31212: 'Service unavailable',
          31213: 'Retry error',
          31214: 'Failed to upload file data',
          31215: 'Failed to upload file metadata',
          31216: 'Failed to download file data',
          31217: 'Failed to download file metadata',
          31218: 'Storage quota exceeded',
          31219: 'Request limit exceeded',
          31220: 'Traffic limit exceeded',
          31298: 'Server response key is invalid',
          31299: 'Server response key does not exist',
        },
      },
      ui: {
        shared_file_title: '[Shared] {0} (read-only)',
        load_share_for_edit: 'Loading shared file...',
        share_sync_success: 'Shared content synced',
        recycle_clear_confirm: 'Clear the recycle bin? Cleared files cannot be restored.',

        fullscreen_exit_hint: 'Press Esc or F11 to exit full screen',

        error_detail: 'Details',
        copy_and_feedback: 'Copy and send feedback',
        move_file_confirm: 'Move "{0}" to "{1}"?',
        rename: 'Rename',
        rename_success: '{0} renamed successfully',
        move_success: '{0} moved to {1}',

        command: {
          appendsiblingnode: 'Add sibling topic',
          appendparentnode: 'Add parent topic',
          appendchildnode: 'Add child topic',
          removenode: 'Delete',
          editnode: 'Edit',
          arrangeup: 'Move up',
          arrangedown: 'Move down',
          resetlayout: 'Reset layout',
          expandtoleaf: 'Expand all nodes',
          expandtolevel1: 'Expand to level 1',
          expandtolevel2: 'Expand to level 2',
          expandtolevel3: 'Expand to level 3',
          expandtolevel4: 'Expand to level 4',
          expandtolevel5: 'Expand to level 5',
          expandtolevel6: 'Expand to level 6',
          fullscreen: 'Full screen',
          outline: 'Outline',
        },

        search: 'Search',

        expandtoleaf: 'Expand',

        back: 'Back',

        undo: 'Undo (Ctrl + Z)',
        redo: 'Redo (Ctrl + Y)',

        tabs: {
          idea: 'Idea',
          appearence: 'Appearance',
          view: 'View',
        },

        quickvisit: {
          new: 'New (Ctrl + Alt + N)',
          save: 'Save (Ctrl + S)',
          share: 'Share (Ctrl + Alt + S)',
          feedback: 'Feedback (F1)',
          editshare: 'Edit',
        },

        menu: {
          mainmenutext: 'Mind Map',

          newtab: 'New',
          opentab: 'Open',
          savetab: 'Save',
          sharetab: 'Share',
          preferencetab: 'Settings',
          helptab: 'Help',
          feedbacktab: 'Feedback',
          recenttab: 'Recent',
          netdisktab: 'Cloud Storage',
          localtab: 'Local File',
          drafttab: 'Drafts',
          downloadtab: 'Export Locally',
          createsharetab: 'Current Mind Map',
          managesharetab: 'Shared',

          newheader: 'New Mind Map',
          openheader: 'Open',
          saveheader: 'Save To',
          draftheader: 'Drafts',
          shareheader: 'Share My Mind Map',
          downloadheader: 'Export to Format',
          preferenceheader: 'Preferences',
          helpheader: 'Help',
          feedbackheader: 'Feedback',
        },

        mydocument: 'My Documents',
        emptydir: 'This folder is empty.',
        pickfile: 'Choose file...',
        acceptfile: 'Supported formats: {0}',
        dropfile: 'or drop a file here',
        unsupportedfile: 'Unsupported file format',
        untitleddoc: 'Untitled Document',
        overrideconfirm: '{0} already exists. Overwrite it?',
        checklogin: 'Checking sign-in status...',
        loggingin: 'Signing in...',
        recent: 'Recently Opened',
        clearrecent: 'Clear',
        clearrecentconfirm: 'Clear the recent documents list?',
        cleardraft: 'Clear',
        cleardraftconfirm: 'Clear drafts?',

        none_share: 'Do not share',
        public_share: 'Public share',
        password_share: 'Private share',
        email_share: 'Email invitation',
        url_share: 'Mind map URL:',
        sns_share: 'Share on social networks:',
        sns_share_text:
          '"{0}" - A mind map I created. Take a look: {1}',
        none_share_description: 'Do not share the current mind map',
        public_share_description: 'Create a share anyone can view',
        share_button_text: 'Create',
        password_share_description: 'Create a share that requires a password',
        email_share_description: 'Create a share for selected people and optionally allow editing',
        ondev: 'Coming soon.',
        create_share_failed: 'Share failed: {0}',
        remove_share_failed: 'Remove failed: {1}',
        copy: 'Copy',
        copied: 'Copied',
        shared_tip:
          'This mind map was shared by {0}. You can edit it and save it to your own cloud drive or share it again.',
        current_share: 'Current Mind Map',
        manage_share: 'My Shares',
        share_remove_action: 'Stop sharing this mind map',
        share_view_action: 'Open share link',
        share_edit_action: 'Edit shared file',

        login: 'Sign in',
        logout: 'Sign out',
        switchuser: 'Switch account',
        userinfo: 'Profile',
        gotonetdisk: 'My Cloud Drive',
        requirelogin: 'Please <a class="login-button">sign in</a> to continue',
        saveas: 'Save As',
        filename: 'File Name',
        fileformat: 'File Format',
        save: 'Save',
        mkdir: 'New Folder',
        recycle: 'Recycle Bin',
        newdir: 'Untitled Folder',

        bold: 'Bold',
        italic: 'Italic',
        forecolor: 'Text Color',
        fontfamily: 'Font',
        fontsize: 'Font Size',
        layoutstyle: 'Theme',
        node: 'Node',
        saveto: 'Save To',
        hand: 'Enable Dragging',
        camera: 'Center Root Node',
        'zoom-in': 'Zoom In (Ctrl+)',
        'zoom-out': 'Zoom Out (Ctrl-)',
        markers: 'Markers',
        resource: 'Resource',
        help: 'Help',
        preference: 'Preferences',
        expandnode: 'Expand to Leaves',
        collapsenode: 'Collapse to Level 1',
        template: 'Template',
        theme: 'Theme',
        clearstyle: 'Clear Style',
        copystyle: 'Copy Style',
        pastestyle: 'Paste Style',
        appendsiblingnode: 'Sibling Topic',
        appendchildnode: 'Child Topic',
        arrangeup: 'Move Forward',
        arrangedown: 'Move Backward',
        editnode: 'Edit Node',
        removenode: 'Remove Node',
        priority: 'Priority',
        progress: {
          p1: 'Not Started',
          p2: '1/8 Complete',
          p3: '1/4 Complete',
          p4: '3/8 Complete',
          p5: 'Half Complete',
          p6: '5/8 Complete',
          p7: '3/4 Complete',
          p8: '7/8 Complete',
          p9: 'Complete',
          p0: 'Clear Progress',
        },
        link: 'Link',
        image: 'Image',
        note: 'Note',
        insertlink: 'Insert Link',
        insertimage: 'Insert Image',
        insertnote: 'Insert Note',
        removelink: 'Remove Link',
        removeimage: 'Remove Image',
        removenote: 'Remove Note',
        resetlayout: 'Reset Layout',

        justnow: 'Just now',
        minutesago: '{0} minutes ago',
        hoursago: '{0} hours ago',
        yesterday: 'Yesterday',
        daysago: '{0} days ago',
        longago: 'A long time ago',

        redirect:
          'You are opening the link {0}. The mind map editor cannot guarantee that it is safe. Continue?',
        navigator: 'Navigator',

        unsavedcontent:
          'The current file has not been saved to cloud storage:\n\n{0}\n\nUnsaved data is cached in drafts, but clearing the browser cache will remove drafts.',

        shortcuts: 'Shortcuts',
        contact: 'Contact and Feedback',
        email: 'Mailing List',
        qq_group: 'QQ Group',
        github_issue: 'Github',
        baidu_tieba: 'Baidu Tieba',

        clipboardunsupported: 'Your browser does not support the clipboard. Please use the keyboard shortcut to copy.',

        load_success: '{0} loaded successfully',
        save_success: '{0} saved to {1}',
        autosave_success: '{0} autosaved to {1}',

        selectall: 'Select All',
        selectrevert: 'Invert Selection',
        selectsiblings: 'Select Siblings',
        selectlevel: 'Select Same Level',
        selectpath: 'Select Path',
        selecttree: 'Select Subtree',
      },
      popupcolor: {
        clearColor: 'Clear Color',
        standardColor: 'Standard Color',
        themeColor: 'Theme Color',
      },
      dialogs: {
        markers: {
          static: {
            lang_input_text: 'Text:',
            lang_input_url: 'URL:',
            lang_input_title: 'Title:',
            lang_input_target: 'Target:',
          },
          priority: 'Priority',
          none: 'None',
          progress: {
            title: 'Progress',
            notdone: 'Not Done',
            done1: '1/8 Complete',
            done2: '1/4 Complete',
            done3: '3/8 Complete',
            done4: 'Half Complete',
            done5: '5/8 Complete',
            done6: '3/4 Complete',
            done7: '7/8 Complete',
            done: 'Done',
          },
        },
        help: {},
        hyperlink: {},
        image: {},
        resource: {},
      },
      hyperlink: {
        hyperlink: 'Hyperlink...',
        unhyperlink: 'Remove Hyperlink',
      },
      image: {
        image: 'Image...',
        removeimage: 'Remove Image',
      },
      marker: {
        marker: 'Progress/Priority...',
      },
      resource: {
        resource: 'Resource...',
      },
    },
  };
});
